In [1]:
import numpy as np
import pandas as pd
import pickle

In [2]:
pd.set_option("display.max_columns", 101)
pd.set_option("display.max_rows", 73)

In [3]:
# team_df = pd.read_pickle('data/team_stats_scraped.pickle')
sched_df = pd.read_pickle('data/games_scraped.pickle')

In [4]:
sched_df.shape

(29399, 25)

In [5]:
mask = (sched_df.team == 'chi') & (sched_df.year == 2019)
sched_df[mask]

,team,year,opp,game_day_of_week,game_date,game_outcome,team_record,game_location,pts_off,pts_def,first_down_off,yards_off,pass_yds_off,rush_yds_off,to_off,first_down_def,yards_def,pass_yds_def,rush_yds_def,to_def,game_time,overtime,exp_pts_off,exp_pts_def,exp_pts_st
4819,chi,2019,gnb,Thu,September,L,0-1,NaN,3.0,10.0,16.0,254.0,208.0,46.0,1.0,13.0,213.0,166.0,47.0,NaN,8.0,NaN,-20.0,9.0,-2.0
4820,chi,2019,den,Sun,September,W,1-1,@,16.0,14.0,18.0,273.0,120.0,153.0,NaN,27.0,372.0,282.0,90.0,1.0,4.0,NaN,4.0,-4.0,5.0
4821,chi,2019,was,Mon,September,W,2-1,@,31.0,15.0,21.0,298.0,208.0,90.0,1.0,25.0,356.0,287.0,69.0,5.0,8.0,NaN,9.0,11.0,-3.0
4822,chi,2019,min,Sun,September,W,3-1,NaN,16.0,6.0,17.0,269.0,197.0,72.0,NaN,15.0,222.0,182.0,40.0,2.0,4.0,NaN,-2.0,10.0,1.0
4823,chi,2019,rai,Sun,October,L,3-2,@,21.0,24.0,15.0,236.0,194.0,42.0,2.0,25.0,398.0,229.0,169.0,2.0,1.0,NaN,-3.0,-2.0,-0.0
4824,chi,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4825,chi,2019,nor,Sun,October,L,3-3,NaN,25.0,36.0,16.0,252.0,235.0,17.0,2.0,24.0,424.0,273.0,151.0,NaN,4.0,NaN,-12.0,-13.0,10.0
4826,chi,2019,sdg,Sun,October,L,3-4,NaN,16.0,17.0,26.0,388.0,226.0,162.0,2.0,11.0,231.0,195.0,36.0,1.0,1.0,NaN,0.0,5.0,-6.0
4827,chi,2019,phi,Sun,November,L,3-5,@,14.0,22.0,10.0,164.0,102.0,62.0,1.0,26.0,373.0,227.0,146.0,NaN,1.0,NaN,-4.0,-10.0,2.0
4828,chi,2019,det,Sun,November,W,4-5,NaN,20.0,13.0,13.0,226.0,145.0,81.0,NaN,21.0,357.0,259.0,98.0,1.0,1.0,NaN,-0.0,6.0,-2.0
4829,chi,2019,ram,Sun,November,L,4-6,@,7.0,17.0,17.0,267.0,193.0,74.0,1.0,13.0,283.0,173.0,110.0,2.0,8.0,NaN,-13.0,5.0,-5.0
4830,chi,2019,nyg,Sun,November,W,5-6,NaN,19.0,14.0,20.0,335.0,270.0,65.0,2.0,14.0,243.0,134.0,109.0,1.0,1.0,NaN,-7.0,12.0,-2.0
4831,chi,2019,det,Thu,November,W,6-6,@,24.0,20.0,22.0,419.0,331.0,88.0,1.0,19.0,364.0,259.0,105.0,1.0,12.0,NaN,8.0,-6.0,0.0
4832,chi,2019,dal,Thu,December,W,7-6,NaN,31.0,24.0,24.0,382.0,231.0,151.0,2.0,22.0,408.0,326.0,82.0,NaN,8.0,NaN,10.0,-10.0,8.0
4833,chi,2019,gnb,Sun,December,L,7-7,@,13.0,21.0,20.0,415.0,319.0,96.0,3.0,12.0,292.0,192.0,100.0,NaN,1.0,NaN,-4.0,2.0,-1.0
4834,chi,2019,kan,Sun,December,L,7-8,NaN,3.0,26.0,18.0,234.0,133.0,101.0,NaN,25.0,350.0,244.0,106.0,NaN,8.0,NaN,-6.0,-14.0,-1.0
4835,chi,2019,min,Sun,December,W,8-8,@,21.0,19.0,24.0,337.0,179.0,158.0,1.0,14.0,300.0,126.0,174.0,3.0,1.0,NaN,1.0,-2.0,-1.0

In [6]:
# clean the game_location column & apply change. def home_game(row):
def home_game(row):    
    if row == '@':
        return 1
    return 0

sched_df['home'] = sched_df.game_location.apply(home_game)
sched_df.drop("game_location", axis=1, errors='ignore', inplace=True)

In [7]:
sched_df[mask]

,team,year,opp,game_day_of_week,game_date,game_outcome,team_record,pts_off,pts_def,first_down_off,yards_off,pass_yds_off,rush_yds_off,to_off,first_down_def,yards_def,pass_yds_def,rush_yds_def,to_def,game_time,overtime,exp_pts_off,exp_pts_def,exp_pts_st,home
4819,chi,2019,gnb,Thu,September,L,0-1,3.0,10.0,16.0,254.0,208.0,46.0,1.0,13.0,213.0,166.0,47.0,NaN,8.0,NaN,-20.0,9.0,-2.0,0
4820,chi,2019,den,Sun,September,W,1-1,16.0,14.0,18.0,273.0,120.0,153.0,NaN,27.0,372.0,282.0,90.0,1.0,4.0,NaN,4.0,-4.0,5.0,1
4821,chi,2019,was,Mon,September,W,2-1,31.0,15.0,21.0,298.0,208.0,90.0,1.0,25.0,356.0,287.0,69.0,5.0,8.0,NaN,9.0,11.0,-3.0,1
4822,chi,2019,min,Sun,September,W,3-1,16.0,6.0,17.0,269.0,197.0,72.0,NaN,15.0,222.0,182.0,40.0,2.0,4.0,NaN,-2.0,10.0,1.0,0
4823,chi,2019,rai,Sun,October,L,3-2,21.0,24.0,15.0,236.0,194.0,42.0,2.0,25.0,398.0,229.0,169.0,2.0,1.0,NaN,-3.0,-2.0,-0.0,1
4824,chi,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4825,chi,2019,nor,Sun,October,L,3-3,25.0,36.0,16.0,252.0,235.0,17.0,2.0,24.0,424.0,273.0,151.0,NaN,4.0,NaN,-12.0,-13.0,10.0,0
4826,chi,2019,sdg,Sun,October,L,3-4,16.0,17.0,26.0,388.0,226.0,162.0,2.0,11.0,231.0,195.0,36.0,1.0,1.0,NaN,0.0,5.0,-6.0,0
4827,chi,2019,phi,Sun,November,L,3-5,14.0,22.0,10.0,164.0,102.0,62.0,1.0,26.0,373.0,227.0,146.0,NaN,1.0,NaN,-4.0,-10.0,2.0,1
4828,chi,2019,det,Sun,November,W,4-5,20.0,13.0,13.0,226.0,145.0,81.0,NaN,21.0,357.0,259.0,98.0,1.0,1.0,NaN,-0.0,6.0,-2.0,0
4829,chi,2019,ram,Sun,November,L,4-6,7.0,17.0,17.0,267.0,193.0,74.0,1.0,13.0,283.0,173.0,110.0,2.0,8.0,NaN,-13.0,5.0,-5.0,1
4830,chi,2019,nyg,Sun,November,W,5-6,19.0,14.0,20.0,335.0,270.0,65.0,2.0,14.0,243.0,134.0,109.0,1.0,1.0,NaN,-7.0,12.0,-2.0,0
4831,chi,2019,det,Thu,November,W,6-6,24.0,20.0,22.0,419.0,331.0,88.0,1.0,19.0,364.0,259.0,105.0,1.0,12.0,NaN,8.0,-6.0,0.0,1
4832,chi,2019,dal,Thu,December,W,7-6,31.0,24.0,24.0,382.0,231.0,151.0,2.0,22.0,408.0,326.0,82.0,NaN,8.0,NaN,10.0,-10.0,8.0,0
4833,chi,2019,gnb,Sun,December,L,7-7,13.0,21.0,20.0,415.0,319.0,96.0,3.0,12.0,292.0,192.0,100.0,NaN,1.0,NaN,-4.0,2.0,-1.0,1
4834,chi,2019,kan,Sun,December,L,7-8,3.0,26.0,18.0,234.0,133.0,101.0,NaN,25.0,350.0,244.0,106.0,NaN,8.0,NaN,-6.0,-14.0,-1.0,0
4835,chi,2019,min,Sun,December,W,8-8,21.0,19.0,24.0,337.0,179.0,158.0,1.0,14.0,300.0,126.0,174.0,3.0,1.0,NaN,1.0,-2.0,-1.0,1

In [8]:
# add team_year identifier to each row (to easily groupby team/year)

team_years = sched_df['team'] + '-' +  sched_df['year'].astype(str) 
sched_df.insert(loc=2, column='team_year', value=team_years)
sched_df

,team,year,team_year,opp,game_day_of_week,game_date,game_outcome,team_record,pts_off,pts_def,first_down_off,yards_off,pass_yds_off,rush_yds_off,to_off,first_down_def,yards_def,pass_yds_def,rush_yds_def,to_def,game_time,overtime,exp_pts_off,exp_pts_def,exp_pts_st,home
0,crd,1960,crd-1960,ram,Fri,September,W,1-0,43.0,21.0,20.0,430.0,281.0,149.0,5.0,16.0,238.0,188.0,50.0,6.0,NaN,NaN,NaN,NaN,NaN,1
1,crd,1960,crd-1960,nyg,Sun,October,L,1-1,14.0,35.0,11.0,222.0,115.0,107.0,5.0,18.0,405.0,268.0,137.0,6.0,NaN,NaN,NaN,NaN,NaN,0
2,crd,1960,crd-1960,phi,Sun,October,L,1-2,27.0,31.0,20.0,364.0,145.0,219.0,6.0,14.0,293.0,199.0,94.0,3.0,NaN,NaN,NaN,NaN,NaN,1
3,crd,1960,crd-1960,pit,Sun,October,L,1-3,14.0,27.0,20.0,295.0,154.0,141.0,6.0,12.0,237.0,146.0,91.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4,crd,1960,crd-1960,dal,Sun,October,W,2-3,12.0,10.0,17.0,306.0,80.0,226.0,3.0,9.0,175.0,124.0,51.0,2.0,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29394,was,2020,was-2020,sea,Sun,December,L,6-8,15.0,20.0,26.0,353.0,269.0,84.0,2.0,16.0,302.0,121.0,181.0,1.0,1.0,NaN,1.0,-3.0,-4.0,0
29395,was,2020,was-2020,car,Sun,December,L,6-9,13.0,20.0,20.0,386.0,278.0,108.0,4.0,19.0,280.0,167.0,113.0,2.0,4.0,NaN,-5.0,5.0,-7.0,0
29396,was,2020,was-2020,phi,Sun,January,W,7-9,20.0,14.0,16.0,248.0,145.0,103.0,2.0,16.0,216.0,98.0,118.0,3.0,8.0,NaN,-8.0,11.0,3.0,1
29397,was,2020,was-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
29398,was,2020,was-2020,tam,Sat,January,L,7-10,23.0,31.0,23.0,375.0,289.0,86.0,1.0,26.0,507.0,365.0,142.0,1.0,8.0,NaN,5.0,-14.0,1.0,0

In [9]:
# now we need to add a week_num column
sched_df[mask]

,team,year,team_year,opp,game_day_of_week,game_date,game_outcome,team_record,pts_off,pts_def,first_down_off,yards_off,pass_yds_off,rush_yds_off,to_off,first_down_def,yards_def,pass_yds_def,rush_yds_def,to_def,game_time,overtime,exp_pts_off,exp_pts_def,exp_pts_st,home
4819,chi,2019,chi-2019,gnb,Thu,September,L,0-1,3.0,10.0,16.0,254.0,208.0,46.0,1.0,13.0,213.0,166.0,47.0,NaN,8.0,NaN,-20.0,9.0,-2.0,0
4820,chi,2019,chi-2019,den,Sun,September,W,1-1,16.0,14.0,18.0,273.0,120.0,153.0,NaN,27.0,372.0,282.0,90.0,1.0,4.0,NaN,4.0,-4.0,5.0,1
4821,chi,2019,chi-2019,was,Mon,September,W,2-1,31.0,15.0,21.0,298.0,208.0,90.0,1.0,25.0,356.0,287.0,69.0,5.0,8.0,NaN,9.0,11.0,-3.0,1
4822,chi,2019,chi-2019,min,Sun,September,W,3-1,16.0,6.0,17.0,269.0,197.0,72.0,NaN,15.0,222.0,182.0,40.0,2.0,4.0,NaN,-2.0,10.0,1.0,0
4823,chi,2019,chi-2019,rai,Sun,October,L,3-2,21.0,24.0,15.0,236.0,194.0,42.0,2.0,25.0,398.0,229.0,169.0,2.0,1.0,NaN,-3.0,-2.0,-0.0,1
4824,chi,2019,chi-2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4825,chi,2019,chi-2019,nor,Sun,October,L,3-3,25.0,36.0,16.0,252.0,235.0,17.0,2.0,24.0,424.0,273.0,151.0,NaN,4.0,NaN,-12.0,-13.0,10.0,0
4826,chi,2019,chi-2019,sdg,Sun,October,L,3-4,16.0,17.0,26.0,388.0,226.0,162.0,2.0,11.0,231.0,195.0,36.0,1.0,1.0,NaN,0.0,5.0,-6.0,0
4827,chi,2019,chi-2019,phi,Sun,November,L,3-5,14.0,22.0,10.0,164.0,102.0,62.0,1.0,26.0,373.0,227.0,146.0,NaN,1.0,NaN,-4.0,-10.0,2.0,1
4828,chi,2019,chi-2019,det,Sun,November,W,4-5,20.0,13.0,13.0,226.0,145.0,81.0,NaN,21.0,357.0,259.0,98.0,1.0,1.0,NaN,-0.0,6.0,-2.0,0
4829,chi,2019,chi-2019,ram,Sun,November,L,4-6,7.0,17.0,17.0,267.0,193.0,74.0,1.0,13.0,283.0,173.0,110.0,2.0,8.0,NaN,-13.0,5.0,-5.0,1
4830,chi,2019,chi-2019,nyg,Sun,November,W,5-6,19.0,14.0,20.0,335.0,270.0,65.0,2.0,14.0,243.0,134.0,109.0,1.0,1.0,NaN,-7.0,12.0,-2.0,0
4831,chi,2019,chi-2019,det,Thu,November,W,6-6,24.0,20.0,22.0,419.0,331.0,88.0,1.0,19.0,364.0,259.0,105.0,1.0,12.0,NaN,8.0,-6.0,0.0,1
4832,chi,2019,chi-2019,dal,Thu,December,W,7-6,31.0,24.0,24.0,382.0,231.0,151.0,2.0,22.0,408.0,326.0,82.0,NaN,8.0,NaN,10.0,-10.0,8.0,0
4833,chi,2019,chi-2019,gnb,Sun,December,L,7-7,13.0,21.0,20.0,415.0,319.0,96.0,3.0,12.0,292.0,192.0,100.0,NaN,1.0,NaN,-4.0,2.0,-1.0,1
4834,chi,2019,chi-2019,kan,Sun,December,L,7-8,3.0,26.0,18.0,234.0,133.0,101.0,NaN,25.0,350.0,244.0,106.0,NaN,8.0,NaN,-6.0,-14.0,-1.0,0
4835,chi,2019,chi-2019,min,Sun,December,W,8-8,21.0,19.0,24.0,337.0,179.0,158.0,1.0,14.0,300.0,126.0,174.0,3.0,1.0,NaN,1.0,-2.0,-1.0,1