In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import seaborn as sns
sns.set()

from clean import clean_games1
from clean3 import clean_games

pd.set_option("display.max_columns", 250)
pd.set_option("display.max_rows", 73)

For some reason, the detailed dataset on the pro football reference website does not include turnovers. I started off with a different table on their website that did have that. Luckily, I still have it, so I can merge them manually.

In [2]:
df = clean_games('data/games.pickle', start_year=1990)

In [12]:
temp_df = pd.read_pickle('data/games_scraped.pickle')

In [13]:
game_df = df.copy()

In [14]:
mask = game_df['game_id'] == 'den-was-2001-11-18'
game_df[mask]

,game_id,season_year,week_num,team_year,full_game_date,team,decade,opp,game_day_of_week,game_outcome,pts_off,margin,pts_def,pass_cmp,pass_att,pass_yds,pass_td,pass_int,pass_sacked,pass_sacked_yds,pass_yds_per_att,pass_net_yds_per_att,pass_cmp_perc,pass_rating,rush_att,rush_yds,rush_yds_per_att,rush_td,fgm,fga,xpm,xpa,punt,punt_yds,overtime,time_of_poss,third_down_success,third_down_att,fourth_down_success,fourth_down_att,team_home_game,pass_cmp_def,pass_att_def,pass_yds_def,pass_td_def,pass_int_def,pass_sacked_def,pass_sacked_yds_def,pass_yds_per_att_def,pass_net_yds_per_att_def,pass_cmp_perc_def,pass_rating_def,rush_att_def,rush_yds_def,rush_yds_per_att_def,rush_td_def,fgm_def,fga_def,third_down_success_def,third_down_att_def,fourth_down_success_def,fourth_down_att_def,result_tie,result_win,prev_week_num,prev_result_win,off_bye,roll3_wins,ewma19_pts_off,ewma19_margin,ewma19_pts_def,ewma19_pass_cmp,ewma19_pass_att,ewma19_pass_yds,ewma19_pass_td,ewma19_pass_int,ewma19_pass_sacked,ewma19_pass_sacked_yds,ewma19_pass_yds_per_att,ewma19_pass_cmp_perc,ewma19_pass_rating,ewma19_rush_att,ewma19_rush_yds,ewma19_rush_yds_per_att,ewma19_rush_td,ewma19_fgm,ewma19_fga,ewma19_third_down_success,ewma19_third_down_att,ewma19_fourth_down_success,ewma19_fourth_down_att,ewma19_team_home_game,ewma19_result_tie,ewma19_result_win,ewma19_pass_cmp_def,ewma19_pass_att_def,ewma19_pass_yds_def,ewma19_pass_td_def,ewma19_pass_int_def,ewma19_pass_sacked_def,ewma19_pass_sacked_yds_def,ewma19_pass_yds_per_att_def,ewma19_pass_net_yds_per_att_def,ewma19_pass_cmp_perc_def,ewma19_pass_rating_def,ewma19_rush_att_def,ewma19_rush_yds_def,ewma19_rush_yds_per_att_def,ewma19_rush_td_def,ewma19_fgm_def,ewma19_fga_def,ewma19_third_down_success_def,ewma19_third_down_att_def,ewma19_fourth_down_success_def,ewma19_fourth_down_att_def,ewma19_fga_opp,ewma19_fga_def_opp,ewma19_fgm_opp,ewma19_fgm_def_opp,ewma19_fourth_down_att_opp,ewma19_fourth_down_att_def_opp,ewma19_fourth_down_success_opp,ewma19_fourth_down_success_def_opp,ewma19_margin_opp,ewma19_pass_att_opp,ewma19_pass_att_def_opp,ewma19_pass_cmp_opp,ewma19_pass_cmp_def_opp,ewma19_pass_cmp_perc_opp,ewma19_pass_cmp_perc_def_opp,ewma19_pass_int_opp,ewma19_pass_int_def_opp,ewma19_pass_net_yds_per_att_def_opp,ewma19_pass_rating_opp,ewma19_pass_rating_def_opp,ewma19_pass_sacked_opp,ewma19_pass_sacked_def_opp,ewma19_pass_sacked_yds_opp,ewma19_pass_sacked_yds_def_opp,ewma19_pass_td_opp,ewma19_pass_td_def_opp,ewma19_pass_yds_opp,ewma19_pass_yds_def_opp,ewma19_pass_yds_per_att_opp,ewma19_pass_yds_per_att_def_opp,ewma19_pts_def_opp,ewma19_pts_off_opp,ewma19_result_tie_opp,ewma19_result_win_opp,ewma19_rush_att_opp,ewma19_rush_att_def_opp,ewma19_rush_td_opp,ewma19_rush_td_def_opp,ewma19_rush_yds_opp,ewma19_rush_yds_def_opp,ewma19_rush_yds_per_att_opp,ewma19_rush_yds_per_att_def_opp,ewma19_team_home_game_opp,ewma19_third_down_att_opp,ewma19_third_down_att_def_opp,ewma19_third_down_success_opp,ewma19_third_down_success_def_opp,fga_def_opp,fgm_def_opp,fourth_down_att_def_opp,fourth_down_success_def_opp,pass_att_def_opp,pass_cmp_def_opp,pass_cmp_perc_def_opp,pass_int_def_opp,pass_net_yds_per_att_def_opp,pass_rating_def_opp,pass_sacked_def_opp,pass_sacked_yds_def_opp,pass_td_def_opp,pass_yds_def_opp,pass_yds_per_att_def_opp,prev_result_win_opp,prev_week_num_opp,pts_def_opp,roll3_wins_opp,rush_att_def_opp,rush_td_def_opp,rush_yds_def_opp,rush_yds_per_att_def_opp,third_down_att_def_opp,third_down_success_def_opp
3822,den-was-2001-11-18,2001,10.0,den-2001,2001-11-18,den,200,was,Sun,L,10.0,-7.0,17.0,11.0,31.0,98.0,1.0,0.0,3.0,16.0,3.0,2.0,35.0,55.0,27.0,88.0,3.0,0.0,1.0,1.0,1.0,1.0,9.0,351.0,NaN,26:40,5.0,16.0,0.0,1.0,1.0,16.0,31.0,127.0,2.0,0.0,3.0,23.0,4.0,3.0,51.0,83.0,32.0,118.0,3.0,0.0,1.0,1.0,5.0,15.0,0.0,0.0,0.0,0.0,9.0,1.0,0,2.0,24.098,1.357,22.74,21.154,32.594,215.714,1.993,1.388,2.844,16.021,6.823,64.154,86.799,29.971,113.256,3.492,0.377,1.869,2.205,5.193,13.605,0.303,0.77,0.549,0.0,0.54,19.191,31.983,204.539,1.569,1.984,1.83,13.374,6.499,5.529,59.345,74.665,25.777,102.619,3.548,0.586,1.471,1.541,3.998,11.569,0.225,0.454,1.717,1.621,1.446,1.365,0.603,0.739,0.158,0.187,-5.985,25.067,32.902,13.525,19.771,54.418,58.932,0.913,1.873,6.497,77.709,71.156,2.321,1.527,15.098,9.965,1.199,1.498,161.552,232.277,6.753,7.047,22.207,16.222,0.0,0.476,27.945,31.611,0.176,0.797,120.008,125.009,3.678,3.647,0.58,13.088,12.955,4.534,5.742,1.0,1.0,1.0,0.0,31.0,11.0,35.0,0.0,2.0,55.0,3.0,16.0,1.0,98.0,3.0,1.0,8.0,10.0,3.0,27.0,0.0,88.0,3.0,16.0,5.0

In [15]:
temp_df

,team,year,opp,week_num,game_day_of_week,game_date,game_outcome,team_record,game_location,pts_off,pts_def,first_down_off,yards_off,pass_yds_off,rush_yds_off,to_off,first_down_def,yards_def,pass_yds_def,rush_yds_def,to_def,game_time,overtime,exp_pts_off,exp_pts_def,exp_pts_st
0,crd,1960,ram,1,Fri,September 23,W,1-0,@,43.0,21.0,20.0,430.0,281.0,149.0,5.0,16.0,238.0,188.0,50.0,6.0,NaN,NaN,NaN,NaN,NaN
1,crd,1960,nyg,2,Sun,October 2,L,1-1,NaN,14.0,35.0,11.0,222.0,115.0,107.0,5.0,18.0,405.0,268.0,137.0,6.0,NaN,NaN,NaN,NaN,NaN
2,crd,1960,phi,3,Sun,October 9,L,1-2,@,27.0,31.0,20.0,364.0,145.0,219.0,6.0,14.0,293.0,199.0,94.0,3.0,NaN,NaN,NaN,NaN,NaN
3,crd,1960,pit,4,Sun,October 16,L,1-3,@,14.0,27.0,20.0,295.0,154.0,141.0,6.0,12.0,237.0,146.0,91.0,NaN,NaN,NaN,NaN,NaN,NaN
4,crd,1960,dal,5,Sun,October 23,W,2-3,NaN,12.0,10.0,17.0,306.0,80.0,226.0,3.0,9.0,175.0,124.0,51.0,2.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29394,was,2020,sea,15,Sun,December 20,L,6-8,NaN,15.0,20.0,26.0,353.0,269.0,84.0,2.0,16.0,302.0,121.0,181.0,1.0,1.0,NaN,1.0,-3.0,-4.0
29395,was,2020,car,16,Sun,December 27,L,6-9,NaN,13.0,20.0,20.0,386.0,278.0,108.0,4.0,19.0,280.0,167.0,113.0,2.0,4.0,NaN,-5.0,5.0,-7.0
29396,was,2020,phi,17,Sun,January 3,W,7-9,@,20.0,14.0,16.0,248.0,145.0,103.0,2.0,16.0,216.0,98.0,118.0,3.0,8.0,NaN,-8.0,11.0,3.0
29397,was,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29398,was,2020,tam,Wild Card,Sat,January 9,L,7-10,NaN,23.0,31.0,23.0,375.0,289.0,86.0,1.0,26.0,507.0,365.0,142.0,1.0,8.0,NaN,5.0,-14.0,1.0

In [16]:
f = r"%B %d-%Y"
full_game_date = temp_df.game_date + "-" + temp_df.year.astype(str)
full_game_date = pd.to_datetime(full_game_date, format=f)
temp_df.insert(loc=2, column="date", value=full_game_date)
temp_df.drop("game_date", axis=1, inplace=True, errors="ignore")

In [17]:
def apply_game_id(row):
    teams = []
    teams.append(str(row["team"]))
    teams.append(str(row["opp"]))
    teams.sort()

    game_id = teams[0] + "-" + teams[1] + "-" + str(row["date"])[:-9]
    return game_id

# insert game_id column using above function
temp_df["game_id"] = temp_df.apply(apply_game_id, axis=1)
temp_df.drop_duplicates(subset=["game_id"], inplace=True)

In [18]:
mask = temp_df.year > 1989

temp_df = temp_df[mask]

In [19]:
merged_df = game_df.merge(right=temp_df[['game_id', 'to_off', 'to_def']],
                        how='left', on='game_id')

In [20]:
mask = merged_df.team_year == 'chi-2019'
merged_df[mask][['week_num', 'team', 'opp', 'to_off', 'to_def']]

      week_num team  opp  to_off  to_def
5572       4.0  chi  min     NaN     2.0
5573       5.0  chi  rai     2.0     2.0
5574       7.0  chi  nor     2.0     NaN
5575       8.0  chi  sdg     2.0     1.0
5576       9.0  chi  phi     1.0     NaN
5577      10.0  chi  det     NaN     1.0
5578      11.0  chi  ram     1.0     2.0
5579      12.0  chi  nyg     2.0     1.0
5580      13.0  chi  det     1.0     1.0
5581      14.0  chi  dal     2.0     NaN
5582      15.0  chi  gnb     3.0     NaN
5583      16.0  chi  kan     NaN     NaN
5584      17.0  chi  min     1.0     3.0